# Generated by Django 5.2.1 on 2025-05-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ctreated_date',
            new_name='created_date',
        ),
    ]
